config/routes.rb
Rails.application.routes.draw do
  root 'iclones#index'
  resources :favorites
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :iclones do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :iclone
end

app/models/iclone.rb
class Iclone < ApplicationRecord
  validates :content, presence: true, length: { maximum: 50 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }, on: :create
  has_many :iclones
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  has_many :favorite_iclones, through: :favorites, source: :iclone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(iclone_id: params[:iclone_id])
    redirect_to iclones_url, notice: "#{favorite.iclone.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to iclones_url, notice: "#{favorite.iclone.user.name}さんのブログをお気に入り解除しました"
  end
  
  def show
    @favorite_iclones = current_user.favorite_iclones
    @user = current_user
  end
end

app/controllers/iclones_controller.rb
class IclonesController < ApplicationController
  before_action :authenticate_user, only: [:edit, :show, :update, :destroy, :new]
  before_action :set_iclone, only: [:edit, :show, :update, :destroy]

  def index
    @iclones = Iclone.all
  end

  def new
    @iclone = Iclone.new
  end

  def create
    @iclone = Iclone.new(iclone_params)
    @iclone.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @iclone.save
        ContactMailer.contact_mail(@iclone).deliver
        redirect_to iclones_path, notice:"#{current_user.name}さんが新規作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(iclone_id: @iclone.id)
  end

  def edit
    unless @iclone.user_id == current_user.id
      redirect_to iclones_path, notice:"編集できません"
    end
  end

  def update
    if @iclone.update(iclone_params)
      redirect_to iclones_path, notice:"更新しました！"
    else
      render :edit
    end
  end

  def destroy
    unless @iclone.user_id == current_user.id
      redirect_to iclones_path, notice:"削除できません"
    else
      redirect_to iclones_path, notice:"削除しました！"
      @iclone.destroy
    end
  end

  def confirm
    @iclone = current_user.iclones.build(iclone_params)
    render :new if @iclone.invalid?
  end

  private
  def iclone_params
    params.require(:iclone).permit(:image, :content, :image_cache)
  end

  def set_iclone
    @iclone = Iclone.find(params[:id])
  end

  def authenticate_user
    unless logged_in?
      redirect_to iclones_path, notice:"ログインしてください！"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログイン失敗！'
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしたよ'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update]
  before_action :same_user_id, only: [:edit, :update]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
      @favorite_iclones = @user.favorite_iclones
  end

  def edit
    unless logged_in?
      redirect_to new_session_path, notice:"ログイン必須"
    end
  end

  def update
    if @user.update(edit_user_params)
      redirect_to user_path, notice:"プロフィール更新したよ☆"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation, :image, :image_cache)
    end

    def edit_user_params
      params.require(:user).permit(:name, :email, :image, :image_cache)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def same_user_id
      unless current_user.id == @user.id
        redirect_to user_path, notice:"エラー"
      end
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/iclones_helper.rb
module IclonesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_iclones_path
    elsif action_name == 'edit'
      iclone_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/show.html.erb
<h3><%= @user.name %>のお気に入りページ</h3>
<% @favorite_iclones.each do |iclone| %>
<hr>
<p><span>ファボツイート内容: </span><%= iclone.content %></p>
<p><span>ファボツイート画像: </span><%=image_tag iclone.image.url %></p>
<% end %>
<%= link_to '戻る', user_path %>

app/views/iclones/_form.html.erb
<div class = "container">
  <div class = "card auth-card">
    <%= form_with(model: @iclone, local: true, url: choose_new_or_edit ) do |form| %>
    <% if @iclone.errors.any? %>
    <div class="alert alert-warning">
      <ul>
        <% @iclone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class="field">
      <%= form.label :image %>
      <%= image_tag(@iclone.image.url) if @iclone.image && @iclone.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>
    <%= form.submit %>
    <% end %>
  </div>
</div>
<%= link_to '一覧へ', iclones_path %>

app/views/iclones/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>
<%= form_with(model: @iclone, local: true) do |form| %>

<%= form.hidden_field :content %>
<p>本文:<%= @iclone.content %></p>

<%= image_tag(@iclone.image.url) if @iclone.image && @iclone.image.url %>
<%= form.hidden_field :image_cache %><br>

<%= form.submit  "登録する" %><br></br>
<%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/iclones/edit.html.erb
<h2>編集する</h2>
<%= render 'form' %>

app/views/iclones/index.html.erb
<div class="index-intro">
  <h1>INDEX</h1>
</div>
<%= link_to '新規投稿', new_iclone_path %>
<div class="feature-area">
  <div class="container">
    <div class="row">
      <% @iclones.each do |iclone| %>
      <div class="col-sm-6 col-md-4">
        <%= image_tag iclone.image.url %><br>
        <%= iclone.user.name %><br>
        <%= iclone.content %><br>
        <% if logged_in? %>
        <%= link_to '詳細', iclone_path(iclone.id),class: "btn btn-default" %>
        <% if iclone.user.id == current_user.id %>
        <%= link_to "編集", edit_iclone_path(iclone.id),class: "btn btn-default" %>
        <%= link_to '削除', iclone_path(iclone.id), method: :delete, data: { confirm: '本当に削除していいですか？' },class: "btn btn-default" %>
        <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/iclones/new.html.erb
<h2>新規投稿する</h2>
<%= render 'form' %>

app/views/iclones/show.html.erb
<p>内容: <%= @iclone.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @iclone.image.url %>
</p>
<%= link_to '一覧へ', iclones_path %>
<% unless @iclone.user_id == current_user.id %>
<% if @favorite.present? %>
<%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
<%= link_to 'お気に入りする', favorites_path(iclone_id: @iclone.id), method: :post, class: 'btn btn-primary' %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskIg</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">Bootstrap</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="logo"><%= link_to "INDEX", iclones_path%></div>
      </div>
      <div id="gnavi" class="collapse navbar-collapse">
        <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user.id), class: 'btn btn-info' %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete,class: 'btn btn-info' %>
        <% else %>
        <%= link_to "Sign up", new_user_path,class: 'btn btn-info' %>
        <%= link_to "Login", new_session_path,class: 'btn btn-info' %>
        <% end %>
      </div>
    </div>
  </nav>
<% if logged_in? %>
   <%= "#{current_user.name}のページ" %>
     <% end %>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= link_to '一覧へ', iclones_path %>
<% if current_user.id == @user.id %>
  <div class = "container">
    <div class = "card auth-card">
      <% if @user.errors.any? %>
        <div class="alert alert-warning" role="alert">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with(model: @user, local: true) do |f| %>
        <%= f.label :name %>
        <p><%= f.text_field :name %></p>
        <%= f.label :email %>
        <p><%= f.email_field :email %></p>
        <div class="field">
          <p><%= f.label :image %></p>
          <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
          <p><%= f.file_field :image %></p>
          <%= f.hidden_field :image_cache %>
        </div>
        <%= f.submit "Update my account" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= link_to '一覧へ', iclones_path %>
<div class = "container">
  <div class = "card auth-card">
    <% if @user.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %>
    <p><%= f.text_field :name %></p>
    <%= f.label :email %>
    <p><%= f.email_field :email %></p>
    <%= f.label :password %>
    <p><%= f.password_field :password %></p>
    <%= f.label :password_confirmation %>
    <p><%= f.password_field :password_confirmation %></p>
    <div class="field">
      <p><%= f.label :image %></p>
      <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
      <p><%= f.file_field :image %></p>
      <%= f.hidden_field :image_cache %>
    </div>
    <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h2><%= @user.name %>のページ</h2>
  <% if @user.image.present? %>
    <p><strong>Image:</strong>
    <%= image_tag @user.image.url %></p>
  <% end %>
    <p>メールアドレス: <%= @user.email %></p>
    <% if logged_in? %>
      <% if current_user.id == @user.id %>
          <p><%= link_to '編集', edit_user_path(@user) %></p>
          <p><%= link_to 'お気に入りへ', favorite_path %></p>
      <% end %>
    <% end %>
<p><%= link_to '一覧へ', iclones_path %></p>